<?php 
return [ 
"CONFIG_ID"   =>   "1",
"CONFIG_PAGE_LIMIT"   =>   "10",
"CONFIG_FRONT_PAGE_LIMIT"   =>   "18",
"CONFIG_FROM_NAME"   =>   "The Eg Store",
"CONFIG_FROMEMAIL"   =>   "info@theegstore.com",
"CONFIG_EMAIL_SIGNATURE"   =>   "Thanks & Regards
The Eg Store",
"CONFIG_REPLY_TO_EMAIL"   =>   "info@theegstore.com",
"CONFIG_STAFF_MAIL"   =>   "info@theegstore.com",
"CONFIG_COPYRIGHT"   =>   "advocosoft",
"CONFIG_META_DESCRIPTION"   =>   "The Eg Store",
"CONFIG_META_TITLE"   =>   "The Eg Store",
"CONFIG_META_KEYWORDS"   =>   "The Eg Store",
"CONFIG_SITE_TITLE"   =>   "The Eg Store",
"CONFIG_POSTAL_ADDRESS"   =>   "51/452, sec-5, Prtap Nagar, 
Sanganer, Jaipur:302033",
"CONFIG_CURRENCY"   =>   "USD",
"CONFIG_TIMEZONE"   =>   "Asia/Kolkata",
"CONFIG_SITE_ON_MAINTENANCE"   =>   "0",
"CONFIG_SITE_EMERGENCY_NOTE"   =>   "<p>Site Under Maintenance</p>",
"CONFIG_PHONE"   =>   "+91 8619279221",
"CONFIG_ALLOWED_IMAGE_TYPE"   =>   "jpeg,gif,jpg,png",
"CONFIG_ALLOWED_IMAGE_MIME_TYPE"   =>   "image/gif,image/jpeg,image/jpg,image/png",
"CONFIG_ALLOWED_DOC_TYPE"   =>   "docx,doc,pdf",
"CONFIG_ALLOWED_DOC_MIME_TYPE"   =>   "application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
"CONFIG_SHIPPING_AMOUNT"   =>   "99",
"CONFIG_GPLUS"   =>   "https://plus.google.com/u/0/",
"CONFIG_TWITTER"   =>   "https://twitter.com/The_EG_Store",
"CONFIG_LINKEDIN"   =>   "https://www.linkedin.com/in/the-eg-store-7a1a41127/",
"CONFIG_THUMBLR"   =>   "https://theegstoreus.tumblr.com/",
"CONFIG_FACEBOOK"   =>   "https://www.facebook.com/theegstore/?ref=bookmarks",
"CONFIG_IMGUR"   =>   "https://imgur.com/user/TheEGStore/posts",
"CONFIG_PINTEREST"   =>   "https://in.pinterest.com/theegstore/",
"CONFIG_CREATED_AT"   =>   "2019-02-23 15:45:45",
"CONFIG_UPDATED_AT"   =>   "2019-02-23 15:45:45",
 ];